# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectvisit',
            options={'ordering': ('subject_identifier', 'visit_schedule_name', 'schedule_name', 'visit_code', 'visit_date')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectvisit',
            unique_together=set([('subject_identifier', 'visit_schedule_name', 'schedule_name', 'visit_code'), ('subject_identifier', 'visit_schedule_name', 'schedule_name', 'visit_date')]),
        ),
    ]
