# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_crypto_fields.fields.encrypted_char_field
import django_crypto_fields.fields.firstname_field
import django_crypto_fields.fields.lastname_field
import edc_base.model.fields.custom_fields
import edc_consent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyconsent',
            name='dob',
            field=models.DateField(help_text='Format is YYYY-MM-DD', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='dummyconsent',
            name='first_name',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='dummyconsent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='dummyconsent',
            name='guardian_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if subject is a minor. Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma then followe by a space. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Guardian's Last and first name (minors only)"),
        ),
        migrations.AddField(
            model_name='dummyconsent',
            name='initials',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(help_text=' (Encryption: RSA local)', max_length=71, null=True, validators=[django.core.validators.RegexValidator(message='Ensure initials consist of letters only in upper case, no spaces.', regex='^[A-Z]{2,3}$')]),
        ),
        migrations.AddField(
            model_name='dummyconsent',
            name='is_dob_estimated',
            field=edc_base.model.fields.custom_fields.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
        migrations.AddField(
            model_name='dummyconsent',
            name='last_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='dummyconsent',
            name='subject_type',
            field=models.CharField(default='subject', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='dob',
            field=models.DateField(help_text='Format is YYYY-MM-DD', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='first_name',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='guardian_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(blank=True, help_text="Required only if subject is a minor. Format is 'LASTNAME, FIRSTNAME'. All uppercase separated by a comma then followe by a space. (Encryption: RSA local)", max_length=71, null=True, validators=[edc_consent.validators.FullNameValidator()], verbose_name="Guardian's Last and first name (minors only)"),
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='initials',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(help_text=' (Encryption: RSA local)', max_length=71, null=True, validators=[django.core.validators.RegexValidator(message='Ensure initials consist of letters only in upper case, no spaces.', regex='^[A-Z]{2,3}$')]),
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='is_dob_estimated',
            field=edc_base.model.fields.custom_fields.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='last_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='historicaldummyconsent',
            name='subject_type',
            field=models.CharField(default='subject', max_length=25),
            preserve_default=False,
        ),
    ]
