# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='report_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
