# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstraction',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='adherencecounselling',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='artregimen',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='arvhistory',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmenthistory',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='crfmetadata',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='death',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='oi',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='oi',
            name='oi_type',
            field=models.CharField(choices=[('CANDIDIASIS_OF_BRONCHI_TRACHEA_ESOPHAGUS_OR_LUNGS', 'Candidiasis of bronchi, trachea, esophagus, or lungs'), ('INVASIVE_CERVICAL_CANCER', 'Invasive cervical cancer'), ('COCCIDIOIDOMYCOSIS', 'Coccidioidomycosis'), ('CRYPTOCOCCOSIS', 'Cryptococcosis'), ('CRYPTOSPORIDIOSIS_CHRONIC_INTESTINAL_GREATER_THAN_1_MONTH_DURATION', 'Cryptosporidiosis, chronic intestinal (greater than 1 months duration)'), ('ENCEPHALOPHALOPAHY_HIV_RELATED', 'Encephalopathy, HIV-related'), ('HERPES_SIMPLEX', 'Herpes simplex: chronic ulcer(s) (greater than 1 month duration); or bronchitis, pneumonitis, or esophagitis'), ('HISTOPLASMOSIS', 'Histoplasmosis'), ('ISOSPORIASIS_CHRONIC_INTESTINAL_GREATER_THAN_1_MONTH_DURATION', 'Isosporiasis, chronic intestinal (greater than 1 months duration)'), ('KAPOSI_SARCOMA', "Kaposi's sarcoma"), ('LYMPHOMA', 'Lymphoma, multiple forms'), ('MYCOBACTERIUM_AVIUM_COMPLEX', 'Mycobacterium avium complex'), ('TUBERCULOSIS', 'Tuberculosis'), ('PNEUMOCYSTIS_JIROVECI_PNEUMONIA', 'Pneumocystis jiroveci pneumonia (PJP)'), ('PNEUMONIA_RECURRENT', 'Pneumonia, recurrent'), ('PROGRESSIVE_MULTILOCAL_LEUKOENCEPHALOPATHY', 'Progressive multifocal leukoencephalopathy'), ('SALMONELLA_SEPTICEMIA_RECURRENT', 'Salmonella septicemia, recurrent'), ('TOXOPLASMOSIS_OF_BRAIN', 'Toxoplasmosis of brain'), ('WASTING_SYNDROME_DUE_TO_HIV', 'Wasting syndrome due to HIV')], max_length=200),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='pregnancyhistory',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='registeredsubject',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisitionmetadata',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectrequisition',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbhistory',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
