# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='caregiver_relation_other',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Caregiver/Next of Kin Relationship: "Other"'),
        ),
    ]
