# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencecounselling',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artrecord',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrytocare',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incare',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labrecord',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oirecord',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregnancyhistory',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbrecord',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whostaging',
            name='nothing_to_report',
            field=models.BooleanField(default=False),
        ),
    ]
