# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0002_auto_20161021_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDummyConsent',
            new_name='HistoricalSubjectConsent',
        ),
        migrations.RenameModel(
            old_name='DummyConsent',
            new_name='SubjectConsent',
        ),
        migrations.AlterModelOptions(
            name='historicalsubjectconsent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical subject consent'},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='subject_identifier',
        ),
    ]
