# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0002_auto_20161029_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adherencecounselling',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='artrecord',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='entrytocare',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='incare',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='labrecord',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='oirecord',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='pregnancyhistory',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='subjectrequisition',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='tbrecord',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='transferrecord',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
        migrations.RenameField(
            model_name='whostaging',
            old_name='nothing_to_report',
            new_name='no_report',
        ),
    ]
