# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0003_auto_20161029_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherencecounselling',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artrecord',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artregimen',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artregimen',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='entrytocare',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='incare',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='labrecord',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oi',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oi',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oirecord',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregnancy',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pregnancyhistory',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subjectrequisition',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tb',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tb',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tbrecord',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whodiagnosis',
            name='no_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whodiagnosis',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='whostaging',
            name='no_report_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
