# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.model.validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0003_auto_20161031_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_date',
            field=models.DateField(blank=True, help_text='Leave blank to use visit date', null=True, validators=[edc_base.model.validators.date.date_not_future]),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='units',
            field=models.CharField(choices=[('%', '%'), ('10^3/uL', '10^3/uL'), ('10^3uL', '10^3uL'), ('10^6/uL', '10^6/uL'), ('cells/ul', 'cells/ul'), ('copies/ml', 'copies/ml'), ('fL', 'fL'), ('g/dL', 'g/dL'), ('g/L', 'g/L'), ('mg/L', 'mg/L'), ('mm/H', 'mm/H'), ('mmol/L', 'mmol/L'), ('ng/ml', 'ng/ml'), ('pg', 'pg'), ('ratio', 'ratio'), ('U/L', 'U/L'), ('umol/L', 'umol/L')], editable=False, max_length=10, null=True),
        ),
    ]
