# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0003_auto_20161021_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='subject_identifier',
            field=models.CharField(default='0000', editable=False, max_length=50, verbose_name='Subject Identifier'),
            preserve_default=False,
        ),
    ]
