# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0004_enrollment_subject_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='study_site',
            field=models.CharField(default='10', editable=False, max_length=10),
        ),
    ]
