# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 04:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0005_auto_20161101_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='losttofollowup',
            name='last_visit_date',
            field=models.DateField(default=datetime.date(2016, 11, 1)),
            preserve_default=False,
        ),
    ]
