# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ba_namotswe', '0006_losttofollowup_last_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incare',
            name='attended',
        ),
    ]
